### PR TITLE
Initial profiler support

### PR DESCRIPTION
**Pull request by haz**
Closes issue #35

### CODE REVIEW

**Comment by sjlevine** [comment]
Very cool, I'll take a look shortly! :-D

**Comment by sjlevine** [comment]
Hey! Finally getting around to testing this :-) Could you please commit and do a pull request for the corresponding changes in `swank-client-js` so I can test? Thanks!

**Comment by haz** [comment]
Already exists I believe...
- https://github.com/sjlevine/swank-client-js/pull/4

Unless you mean something else?

**Comment by sjlevine** [comment]
Oh whoops, didn't see that. I'll check it out, thanks!

**Pull request merged**
