### PR TITLE
Lispworks doesn't support '--load' command line arg

### PR DESCRIPTION
**Pull request by adamweaver**
Although LW doesn’t have a canonical console application name, LW
documentation suggests `lw-console`

### CODE REVIEW

**Comment by haz** [comment]
So it still needs the swank-script passed in as an argument, but just doesn't work with the --load?

**Comment by daewok** [comment]
Another way to deal with this is to not pass arguments to the Lisp on the command line at all, but instead send the necessary init forms to the Lisp's stdin. SLIME's standard init forms (`slime-init-command`) use only code defined in the spec so should work regardless of which Lisp is used.

**Comment by adamweaver** [comment]
@haz, LW (annoyingly) uses '-load' (single dash) instead

**Comment by sjlevine** [comment]
Thanks for this contribution, Adam! This has been merged in. I've finally gotten around to checking out some of your pull requests (apologies for the delay). I'm cherry picking so as to not merge them all at once.

**Pull request closed without merging**
